// lets create a datastorage for restaurant

kababjees = {
    home: [

        "best desi food in town", "best chinese", "best location", "quick reservations"
    ],
    about:

        "We welcome you to explore our taste of the world, in Continental and Chinese delights and that’s even before you get to the variety and excellence, of our barbecue grill. With warmth of service rarely experienced, it is a perfect place to rejoice with family, to soak in the relaxing decor and with deep desire to revisit for once, is never enough. Now with our network of Six branches across the city of lights , it is possible to experience the magic, whilst collect the best of memories much more close to home. Now you can have goodness of Kababjees delivered at home by just ringing us a bell. Call 111-666- 111 for more information",

    orderNow=[
        
            newArrivals={
                dish1: "CHICKEN MASTO KABAB",
            price: 799,
            dish2: "JOJA SHASHLIK BOTI",
            price: 600,
            dish3: "MUTTON KOFTA KABAB",
            price: 735,
            dish4: "TEXAS STICK BOTI",
            price: 599,
            dish5: "MUTTON KEEMA WITH CHOPS",
            price: 695

        },

        starter = {
            dish1: "SPICY MEXICAN WINGS",
            price: 599,
            pieces: 5,
            dish2: "SUPREME NACHOS",
            price: 499,
            dish3: "LAHORI FISH",
            price: 699,
            dish4: "FIGER FISH",
            price: 890,
            dish5: "FISH & CHIPS",
            price: 699,
            dish6: "KABABJEES SPECIAL PRAWN TEMPURA",
            price: 999,
            dish7: "DHAKA CHICKEN",
            price: 599,
            dish8: "DHAKA FISH",
            price: 689,
            dish9: "HUMMUS",
            price: 400,
            dish10: "DYNAMITE PRAWN",
            price: 979,
            dish11: "STRIPS",
            price: 586,
            dish12: "CHEESY STRIPS",
            price: 669,
            dish13: "CHILLI FRIES",
            price: 500,
            dish14: "CHILLI PRAWN",
            price: 799,
            dish15: "DYNAMITE CHILLI PRAWN",
            price: 989
        },
        salads = {
            salad1: "FRESH GREEN SALAD",
            price: 150,
            salad2: "RUSSIAN SALAD",
            price: 220,
            salad3: "RUSSIAN GREEN SALAD",
            price: 100,
            salad4: "AFGHAN SALAD",
            price: 180,
            salad5: "ARAB SALAD",
            price: 150,
            salad6: "BANANA SALAD",
            price: 250,
            salad7: "BEAN SALAD",
            price: 350,
            salad8: "ITALIAN SALAD",
            price: 300,
            salad9: "RAITA",
            price: 140
        },
        soups = {
            soup1: "HOT & SOUR SOUP",
            price: 365,
            soup2: "CORN SOUP",
            price: 225,
            soup3: "HOT & SWEET SOUP",
            price: 375,
            soup4: "CHICKEN CORN SOUP",
            price: 300,
            soup5: "CHICKEN SOUP",
            price: 200

        },
        burgers = {
            burger1: "ZINGER BURGER",
            price: 599,
            burger2: "CHICKEN BURGER",
            price: 199,
            burger3: "BEEF BURGER",
            price: 299,
            burger4: "BEEF GRILLED BURGER",
            price: 299,
            burger5: "CHICKEN GRILLED BURGER",
            price: 399,
            burger6: "CHICKEN JUICY BURGER",
            price: 399,
            burger7: "BEEF JUICY BURGER",
            price: 599,
            burger8: "BARBQ BURGER",
            price: 499,
            burger9: "CRUNCH BURGER",
            price: 599,
            burger10: "SPICY CHICKEN BURGER",
            price: 539

        },
        sandwiches = {
            sandwich1: "BARBQ SANDWICH",
            price: 699,
            sandwich2: "BARBQ GRILLED SANDWICH",
            price: 589,
            sandwich3: "CLUB SANDWICH",
            price: 789,
            sandwich4: "CHICKE SANDWICH",
            price: 499,
            sandwich5: "BARBQ CLUB SANDWICH",
            price: 599
        },
        chickenSteaks = {
            steak1: "GRILLED MOROCCAN CHICKEN STEAK",
            price: 950,
            serve: 1,
            steak1: "GRILLED CHICKEN STEAK",
            price: 999,
            serve: 2,
            steak1: "GRILLED BARBQ CHICKEN STEAK",
            price: 950,
            serve: 2,
            steak1: "GRILLED MUSHROOM CHICKEN STEAK",
            price: 1150,
            serve: 1,
            steak1: "GRILLED TARRAGON CHICKEN STEAK",
            price: 850,
            serve: 4,
            steak1: "AMERICAN CHICKEN STEAK",
            price: 1190,
            serve: 2,
            steak1: "AMERICAN BEEF STEAK",
            price: 990,
            serve: 6,
            steak1: "FRENCH ONION BEEF STEAK",
            price: 1450,
            serve: 4
        },
        chinese = {
            chinese1: "CHICKEN CHILLI DRY WITH FRIED RICE",
            price: 899,
            chinese2: "BEEF CHILLI DRY WITH FRIED RICE",
            price: 999,
            chinese3: "CHICKEN MANCHURIAN WITH FRIED RICE",
            price: 899,
            chinese4: "CHICKEN SPICY GARLIC CHILLI  WITH FRIED RICE",
            price: 999,
            chinese5: "CHICKEN HOT N SOUR  WITH FRIED RICE",
            price: 999,
            chinese6: "CHICKEN CHILLI VEGETABLE WITH FRIED RICE",
            price: 899,
            chinese7: "BEEF CHILLI GRAVY WITH FRIED RICE",
            price: 799,
            chinese8: "CHICKEN CHERRY CHILLI WITH FRIED RICE",
            price: 699,
            chinese9: "VEGETABLE CHOWMEIN",
            price: 599,
            chinese10: "CHICKEN CHOWMEIN",
            price: 899
        },
        italian = {
            dish1: "CHICKEN ALFREDO",
            price: 645,
            dish2: "CHICKEN PESTO PASTA ",
            price: 999,
            dish3: "BOLOGNESE PASTA",
            price: 775,
            dish4: "SPICY SHRIMP FETTUCCINE",
            price: 895,
            dish5: "BEEF ALFREDO",
            price: 745
        },
        desiTarka = {

            dish1: "CHICKEN KARAHI",
            halfPrice: 1199,
            fullPrice: 1699,
            dish2: "CHICKEN BONELESS KARAHI",
            halfPrice: 1199,
            fullPrice: 1499,
            dish3: "CHICKEN PESHAWRI KARAHI",
            halfPrice: 1199,
            fullPrice: 1299,
            dish4: "MUTTON KARAHI",
            halfPrice: 1199,
            fullPrice: 1399,
            dish5: "WHITE CHICKEN KARAHI",
            halfPrice: 1199,
            fullPrice: 1699,
            dish6: "WHITE MUTTON KARAHI",
            halfPrice: 1199,
            fullPrice: 1699,
            dish7: "BEEF KARAHI",
            halfPrice: 1799,
            fullPrice: 1999,
            dish8: "CHICKEN PANEERKARAHI",
            halfPrice: 1199,
            fullPrice: 1699,
            dish9: "CHICKEN HANDII",
            halfPrice: 139,
            fullPrice: 1699,
            dish10: "CHICKEN MAKHNI HANDI",
            halfPrice: 1199,
            fullPrice: 1699,
            dish11: "CHICKEN ROGHNI HANDI",
            halfPrice: 1399,
            fullPrice: 1999,
            dish12: "CHICKENCHEESE HANDI",
            halfPrice: 1299,
            fullPrice: 1590

        },
        friedItems = {
            fried: "NUGGETS",
            price: 399,
            pieces: 8,
            fried: "TENDERPOPS",
            price: 350,
            pieces: 10,
            fried: "TEMPURA",
            price: 299,
            pieces: 6,
            fried: "CHUNKS",
            price: 599,
            pieces: 12
        },
        barBqKabab = {
            kabab1: "CHICKEN KABAB",
            price: 500,
            kabab2: "CHICKEN SPICY KABAB",
            price: 700,
            kabab3: "CHICKEN GOLAKABAB",
            price: 600,
            kabab4: "CHICKEN RESHMI KABAB",
            price: 400,
            kabab5: "CHICKEN SEEKH KABAB",
            price: 700,
            kabab6: "BEEF KABAB",
            price: 500,
            kabab7: "BEEF SEEKH KABAB",
            price: 400,
            kabab8: "BEEF SPICY KABAB",
            price: 500,
            kabab9: "BEEF GOLA KABAB",
            price: 600,
            kabab10: "BEEF RESHMI KABAB",
            price: 399,
            kabab11: "MUTTON KABAB",
            price: 500,
            kabab12: "CHICKEN MALAI KABAB",
            price: 590,
            kabab13: "CHICKEN CHULLU KABAB",
            price: 500,
            kabab14: "CHICKEN BIHARI KABAB",
            price: 660,
            kabab15: "TANDOORI CHICKEN BOTI ",
            price: 990,
            kabab16: "BIHARI BOTI",
            price: 550,
            kabab17: "CHICKEN TIKKA",
            price: 520,
            kabab18: "CHICKEN MALAI TIKKA",
            price: 510,
            kabab19: "FISH TIKKA",
            price: 890,
            kabab20: "PRAWN KABAB",
            price: 210,
            kabab21: "AFGHANI BOTI",
            price: 530,
            kabab22: "LEBANESE BOTI",
            price: 700,
            kabab23: "BEEF BIHARI BOTI",
            price: 550,
            kabab24: "GRILLED BBQ FISH",
            price: 520,
            kabab25: "BBQ PRAWN",
            price: 510,
            kabab26: "CHICKEN SHISH TAWK",
            price: 890,
            kabab27: "MUTTON CHOPS MASALAH",
            price: 210,
            kabab28: "MUTTON BOTI",
            price: 530,
            kabab29: "MUTTON CHOPS NAMKEEN",
            price: 530,
            kabab30: "MUTTON CHOPS",
            price: 530
        },
        platters = {
            familyPlatters: "Rango Kabab, Resmi Kabab, Malai Boti, Tandoori Boti, Chicken Bihari Boti, Fish Tikka, Mutton Ribs, Mutton Karahi, Grill Fish, Chicken Mandi, Kandhari Naan, Plain Naan and Paratha.",
            price: 7499,
            bbqPlatters: "Chicken spicy kabab, rango kabab, malai kabab, gola kabab, and fish kabab",
            price: 1899,
            serves: 2,
            bbqBotiPlatter: "Malai boti, beef bihari boti, chicken bihari boti, labennese boti and tandoor boti",
            price: 2899,
            serves: 2,
        },
        rice = {
            rice1: "CHICKEN FRIED RICE",
            price: 399,
            rice2: "VEGETABLE FRIED RICE",
            price: 349,
            rice3: "EGG FRIED RICE",
            price: 459,
            rice4: "CHINESE MASALA RICE",
            price: 369,
            rice5: "CHICKEN MANDI",
            price: 1099,
            rice6: "MUTTON MANDI",
            price: 1499

        },
        hotTandoor = {
            plainNaan: "Tradition flat bread made with wheat flour and milk.",
            price: 30,
            garlicNaan: "Naan brushed with butter and garlic to give a scrumptious aroma and taste.",
            price: 60,
            roghniNaa: "Naan brushed with butter and sesame seeds.",
            price: 60,
            wholeWheateNaan: "Tradition flat bread made with whole wheat flour and milk.",
            price: 30,
            cheeseNaan: "Beautifully charred outside yet insanely soft, chewy with melting cheese inside.",
            price: 290,
            chapati: "Healthy option, made with whole wheat.",
            price: 25,
            puriParatha: "Deep fried in ghee, made with white flour.",
            price: 60,
            kandhariNaan: "Afghani traditional flat bread.",
            price: 60

        },
        mocktails = {
            kisses: "A perfect blend of strawberries with sourness of lime.",
            price: 265,
            coolingPunch: "A perfect blend of strawberries with sourness of lime.",
            price: 485,
            grpeWine: "A perfect blend of strawberries with sourness of lime.",
            price: 255,
            blueCoda: "A perfect blend of strawberries with sourness of lime.",
            price: 350,
            margarita: "A perfect blend of strawberries with sourness of lime.",
            price: 440,
            zombie: "A perfect blend of strawberries with sourness of lime.",
            price: 200,
            lemonMint: "A perfect blend of strawberries with sourness of lime.",
            price: 200,
            lemonade: "A perfect blend of strawberries with sourness of lime.",
            price: 150,
            coffee: "A perfect blend of strawberries with sourness of lime.",
            price: 205,
            coldCoffee: "A perfect blend of strawberries with sourness of lime.",
            price: 350,
            whiteColada: "A perfect blend of strawberries with sourness of lime.",
            price: 350,
            coffeeWithIceCream: "A perfect blend of strawberries with sourness of lime.",
            price: 500

        },
        desserts = {

            nutellaBrownie: "Gooey chocolate brownies with flavor of nutella in it.",
            price: 200,
            kababjeesChocolateCake: "Gooey chocolate brownies with flavor of nutella in it.",
            price: 600,
            newYorkCheeseCake: "Gooey chocolate brownies with flavor of nutella in it.",
            price: 700,
            ferreroCheeseCake: "Gooey chocolate brownies with flavor of nutella in it.",
            price: 950,
            coffeeCake: "Gooey chocolate brownies with flavor of nutella in it.",
            price: 450,
            redVelvetCake: "Gooey chocolate brownies with flavor of nutella in it.",
            price: 850

        },
        milkShakes = {
            shake1: "STRAWBERRY MILK SHAKE",
            price: 299,
            shake2: "CHOCOLATE MILK SHAKE",
            price: 259,
            shake3: "BANANA MILK SHAKE",
            price: 399,
            shake4: "MANGO MILK SHAKE",
            price: 499,
            shake5: "OREO MILK SHAKE",
            price: 299,
            shake6: "DAIRYMILK MILK SHAKE",
            price: 299,
            shake7: "VANILLA MILK SHAKE",
            price: 299,
            shake8: "BLUEBERRY MILK SHAKE",
            price: 399,
            shake9: "KITKAT MILK SHAKE",
            price: 299,
            shake10: "DATE MILK SHAKE",
            price: 299,
            shake11: "CHEEKO MILK SHAKE",
            price: 159,
            shake12: "PISTA MILK SHAKE",
            price: 169
        },
        hotBeverages = {
            coffee: ["black,espresso,cappuccino"],
            price: 250,
        },
        coldBeverages = {
            drinks: ["sprite,mirinda,coke,pepsi"],
            price: 70
        },
        mineralWater = {
            small: 60,
            large: 90

        },
        branches =
        ["DoDarya,Shaheed Millat Road & north nazimabad"],

        forReservatios = {
            reservationsatkababjeescom
        },


contactInfo = {
    Phone: 021 - 111 - 666 - 111
},

    description =
    {
        "Kababjees, a perfect place to rejoice variety of cuisines with your love ones, to soak in the relaxing decor & desire to revisit for once is never enough"

},
partnership =
    ["foodpanda, jobolo"]

}


let kababjees ={
    {
    home: [

        "best desi food in town", "best chinese", "best location", "quick reservations"
    ],
    about:

        "We welcome you to explore our taste of the world, in Continental and Chinese delights and that’s even before you get to the variety and excellence, of our barbecue grill. With warmth of service rarely experienced, it is a perfect place to rejoice with family, to soak in the relaxing decor and with deep desire to revisit for once, is never enough. Now with our network of Six branches across the city of lights , it is possible to experience the magic, whilst collect the best of memories much more close to home. Now you can have goodness of Kababjees delivered at home by just ringing us a bell. Call 111-666- 111 for more information.",

    orderNow=[
        
            newArrivals={
                dish1: "CHICKEN MASTO KABAB",
            price: 799,
            dish2: "JOJA SHASHLIK BOTI",
            price: 600,
            dish3: "MUTTON KOFTA KABAB",
            price: 735,
            dish4: "TEXAS STICK BOTI",
            price: 599,
            dish5: "MUTTON KEEMA WITH CHOPS",
            price: 695

        },

        starter = {
            dish1: "SPICY MEXICAN WINGS",
            price: 599,
            pieces: 5,
            dish2: "SUPREME NACHOS",
            price: 499,
            dish3: "LAHORI FISH",
            price: 699,
            dish4: "FIGER FISH",
            price: 890,
            dish5: "FISH & CHIPS",
            price: 699,
            dish6: "KABABJEES SPECIAL PRAWN TEMPURA",
            price: 999,
            dish7: "DHAKA CHICKEN",
            price: 599,
            dish8: "DHAKA FISH",
            price: 689,
            dish9: "HUMMUS",
            price: 400,
            dish10: "DYNAMITE PRAWN",
            price: 979,
            dish11: "STRIPS",
            price: 586,
            dish12: "CHEESY STRIPS",
            price: 669,
            dish13: "CHILLI FRIES",
            price: 500,
            dish14: "CHILLI PRAWN",
            price: 799,
            dish15: "DYNAMITE CHILLI PRAWN",
            price: 989
        },
        salads = {
            salad1: "FRESH GREEN SALAD",
            price: 150,
            salad2: "RUSSIAN SALAD",
            price: 220,
            salad3: "RUSSIAN GREEN SALAD",
            price: 100,
            salad4: "AFGHAN SALAD",
            price: 180,
            salad5: "ARAB SALAD",
            price: 150,
            salad6: "BANANA SALAD",
            price: 250,
            salad7: "BEAN SALAD",
            price: 350,
            salad8: "ITALIAN SALAD",
            price: 300,
            salad9: "RAITA",
            price: 140
        },
        soups = {
            soup1: "HOT & SOUR SOUP",
            price: 365,
            soup2: "CORN SOUP",
            price: 225,
            soup3: "HOT & SWEET SOUP",
            price: 375,
            soup4: "CHICKEN CORN SOUP",
            price: 300,
            soup5: "CHICKEN SOUP",
            price: 200

        },
        burgers = {
            burger1: "ZINGER BURGER",
            price: 599,
            burger2: "CHICKEN BURGER",
            price: 199,
            burger3: "BEEF BURGER",
            price: 299,
            burger4: "BEEF GRILLED BURGER",
            price: 299,
            burger5: "CHICKEN GRILLED BURGER",
            price: 399,
            burger6: "CHICKEN JUICY BURGER",
            price: 399,
            burger7: "BEEF JUICY BURGER",
            price: 599,
            burger8: "BARBQ BURGER",
            price: 499,
            burger9: "CRUNCH BURGER",
            price: 599,
            burger10: "SPICY CHICKEN BURGER",
            price: 539

        },
        sandwiches = {
            sandwich1: "BARBQ SANDWICH",
            price: 699,
            sandwich2: "BARBQ GRILLED SANDWICH",
            price: 589,
            sandwich3: "CLUB SANDWICH",
            price: 789,
            sandwich4: "CHICKE SANDWICH",
            price: 499,
            sandwich5: "BARBQ CLUB SANDWICH",
            price: 599
        },
        chickenSteaks = {
            steak1: "GRILLED MOROCCAN CHICKEN STEAK",
            price: 950,
            serve: 1,
            steak1: "GRILLED CHICKEN STEAK",
            price: 999,
            serve: 2,
            steak1: "GRILLED BARBQ CHICKEN STEAK",
            price: 950,
            serve: 2,
            steak1: "GRILLED MUSHROOM CHICKEN STEAK",
            price: 1150,
            serve: 1,
            steak1: "GRILLED TARRAGON CHICKEN STEAK",
            price: 850,
            serve: 4,
            steak1: "AMERICAN CHICKEN STEAK",
            price: 1190,
            serve: 2,
            steak1: "AMERICAN BEEF STEAK",
            price: 990,
            serve: 6,
            steak1: "FRENCH ONION BEEF STEAK",
            price: 1450,
            serve: 4
        },
        chinese = {
            chinese1: "CHICKEN CHILLI DRY WITH FRIED RICE",
            price: 899,
            chinese2: "BEEF CHILLI DRY WITH FRIED RICE",
            price: 999,
            chinese3: "CHICKEN MANCHURIAN WITH FRIED RICE",
            price: 899,
            chinese4: "CHICKEN SPICY GARLIC CHILLI  WITH FRIED RICE",
            price: 999,
            chinese5: "CHICKEN HOT N SOUR  WITH FRIED RICE",
            price: 999,
            chinese6: "CHICKEN CHILLI VEGETABLE WITH FRIED RICE",
            price: 899,
            chinese7: "BEEF CHILLI GRAVY WITH FRIED RICE",
            price: 799,
            chinese8: "CHICKEN CHERRY CHILLI WITH FRIED RICE",
            price: 699,
            chinese9: "VEGETABLE CHOWMEIN",
            price: 599,
            chinese10: "CHICKEN CHOWMEIN",
            price: 899
        },
        italian = {
            dish1: "CHICKEN ALFREDO",
            price: 645,
            dish2: "CHICKEN PESTO PASTA ",
            price: 999,
            dish3: "BOLOGNESE PASTA",
            price: 775,
            dish4: "SPICY SHRIMP FETTUCCINE",
            price: 895,
            dish5: "BEEF ALFREDO",
            price: 745
        },
        desiTarka = {

            dish1: "CHICKEN KARAHI",
            halfPrice: 1199,
            fullPrice: 1699,
            dish2: "CHICKEN BONELESS KARAHI",
            halfPrice: 1199,
            fullPrice: 1499,
            dish3: "CHICKEN PESHAWRI KARAHI",
            halfPrice: 1199,
            fullPrice: 1299,
            dish4: "MUTTON KARAHI",
            halfPrice: 1199,
            fullPrice: 1399,
            dish5: "WHITE CHICKEN KARAHI",
            halfPrice: 1199,
            fullPrice: 1699,
            dish6: "WHITE MUTTON KARAHI",
            halfPrice: 1199,
            fullPrice: 1699,
            dish7: "BEEF KARAHI",
            halfPrice: 1799,
            fullPrice: 1999,
            dish8: "CHICKEN PANEERKARAHI",
            halfPrice: 1199,
            fullPrice: 1699,
            dish9: "CHICKEN HANDII",
            halfPrice: 139,
            fullPrice: 1699,
            dish10: "CHICKEN MAKHNI HANDI",
            halfPrice: 1199,
            fullPrice: 1699,
            dish11: "CHICKEN ROGHNI HANDI",
            halfPrice: 1399,
            fullPrice: 1999,
            dish12: "CHICKENCHEESE HANDI",
            halfPrice: 1299,
            fullPrice: 1590

        },
        friedItems = {
            fried: "NUGGETS",
            price: 399,
            pieces: 8,
            fried: "TENDERPOPS",
            price: 350,
            pieces: 10,
            fried: "TEMPURA",
            price: 299,
            pieces: 6,
            fried: "CHUNKS",
            price: 599,
            pieces: 12
        },
        barBqKabab = {
            kabab1: "CHICKEN KABAB",
            price: 500,
            kabab2: "CHICKEN SPICY KABAB",
            price: 700,
            kabab3: "CHICKEN GOLAKABAB",
            price: 600,
            kabab4: "CHICKEN RESHMI KABAB",
            price: 400,
            kabab5: "CHICKEN SEEKH KABAB",
            price: 700,
            kabab6: "BEEF KABAB",
            price: 500,
            kabab7: "BEEF SEEKH KABAB",
            price: 400,
            kabab8: "BEEF SPICY KABAB",
            price: 500,
            kabab9: "BEEF GOLA KABAB",
            price: 600,
            kabab10: "BEEF RESHMI KABAB",
            price: 399,
            kabab11: "MUTTON KABAB",
            price: 500,
            kabab12: "CHICKEN MALAI KABAB",
            price: 590,
            kabab13: "CHICKEN CHULLU KABAB",
            price: 500,
            kabab14: "CHICKEN BIHARI KABAB",
            price: 660,
            kabab15: "TANDOORI CHICKEN BOTI ",
            price: 990,
            kabab16: "BIHARI BOTI",
            price: 550,
            kabab17: "CHICKEN TIKKA",
            price: 520,
            kabab18: "CHICKEN MALAI TIKKA",
            price: 510,
            kabab19: "FISH TIKKA",
            price: 890,
            kabab20: "PRAWN KABAB",
            price: 210,
            kabab21: "AFGHANI BOTI",
            price: 530,
            kabab22: "LEBANESE BOTI",
            price: 700,
            kabab23: "BEEF BIHARI BOTI",
            price: 550,
            kabab24: "GRILLED BBQ FISH",
            price: 520,
            kabab25: "BBQ PRAWN",
            price: 510,
            kabab26: "CHICKEN SHISH TAWK",
            price: 890,
            kabab27: "MUTTON CHOPS MASALAH",
            price: 210,
            kabab28: "MUTTON BOTI",
            price: 530,
            kabab29: "MUTTON CHOPS NAMKEEN",
            price: 530,
            kabab30: "MUTTON CHOPS",
            price: 530
        },
        platters = {
            familyPlatters: "Rango Kabab, Resmi Kabab, Malai Boti, Tandoori Boti, Chicken Bihari Boti, Fish Tikka, Mutton Ribs, Mutton Karahi, Grill Fish, Chicken Mandi, Kandhari Naan, Plain Naan and Paratha.",
            price: 7499,
            bbqPlatters: "Chicken spicy kabab, rango kabab, malai kabab, gola kabab, and fish kabab",
            price: 1899,
            serves: 2,
            bbqBotiPlatter: "Malai boti, beef bihari boti, chicken bihari boti, labennese boti and tandoor boti",
            price: 2899,
            serves: 2,
        },
        rice = {
            rice1: "CHICKEN FRIED RICE",
            price: 399,
            rice2: "VEGETABLE FRIED RICE",
            price: 349,
            rice3: "EGG FRIED RICE",
            price: 459,
            rice4: "CHINESE MASALA RICE",
            price: 369,
            rice5: "CHICKEN MANDI",
            price: 1099,
            rice6: "MUTTON MANDI",
            price: 1499

        },
        hotTandoor = {
            plainNaan: "Tradition flat bread made with wheat flour and milk.",
            price: 30,
            garlicNaan: "Naan brushed with butter and garlic to give a scrumptious aroma and taste.",
            price: 60,
            roghniNaa: "Naan brushed with butter and sesame seeds.",
            price: 60,
            wholeWheateNaan: "Tradition flat bread made with whole wheat flour and milk.",
            price: 30,
            cheeseNaan: "Beautifully charred outside yet insanely soft, chewy with melting cheese inside.",
            price: 290,
            chapati: "Healthy option, made with whole wheat.",
            price: 25,
            puriParatha: "Deep fried in ghee, made with white flour.",
            price: 60,
            kandhariNaan: "Afghani traditional flat bread.",
            price: 60

        },
        mocktails = {
            kisses: "A perfect blend of strawberries with sourness of lime.",
            price: 265,
            coolingPunch: "A perfect blend of strawberries with sourness of lime.",
            price: 485,
            grpeWine: "A perfect blend of strawberries with sourness of lime.",
            price: 255,
            blueCoda: "A perfect blend of strawberries with sourness of lime.",
            price: 350,
            margarita: "A perfect blend of strawberries with sourness of lime.",
            price: 440,
            zombie: "A perfect blend of strawberries with sourness of lime.",
            price: 200,
            lemonMint: "A perfect blend of strawberries with sourness of lime.",
            price: 200,
            lemonade: "A perfect blend of strawberries with sourness of lime.",
            price: 150,
            coffee: "A perfect blend of strawberries with sourness of lime.",
            price: 205,
            coldCoffee: "A perfect blend of strawberries with sourness of lime.",
            price: 350,
            whiteColada: "A perfect blend of strawberries with sourness of lime.",
            price: 350,
            coffeeWithIceCream: "A perfect blend of strawberries with sourness of lime.",
            price: 500

        },
        desserts = {

            nutellaBrownie: "Gooey chocolate brownies with flavor of nutella in it.",
            price: 200,
            kababjeesChocolateCake: "Gooey chocolate brownies with flavor of nutella in it.",
            price: 600,
            newYorkCheeseCake: "Gooey chocolate brownies with flavor of nutella in it.",
            price: 700,
            ferreroCheeseCake: "Gooey chocolate brownies with flavor of nutella in it.",
            price: 950,
            coffeeCake: "Gooey chocolate brownies with flavor of nutella in it.",
            price: 450,
            redVelvetCake: "Gooey chocolate brownies with flavor of nutella in it.",
            price: 850

        },
        milkShakes = {
            shake1: "STRAWBERRY MILK SHAKE",
            price: 299,
            shake2: "CHOCOLATE MILK SHAKE",
            price: 259,
            shake3: "BANANA MILK SHAKE",
            price: 399,
            shake4: "MANGO MILK SHAKE",
            price: 499,
            shake5: "OREO MILK SHAKE",
            price: 299,
            shake6: "DAIRYMILK MILK SHAKE",
            price: 299,
            shake7: "VANILLA MILK SHAKE",
            price: 299,
            shake8: "BLUEBERRY MILK SHAKE",
            price: 399,
            shake9: "KITKAT MILK SHAKE",
            price: 299,
            shake10: "DATE MILK SHAKE",
            price: 299,
            shake11: "CHEEKO MILK SHAKE",
            price: 159,
            shake12: "PISTA MILK SHAKE",
            price: 169
        },
        hotBeverages = {
            coffee: ["black,espresso,cappuccino"],
            price: 250,
        },
        coldBeverages = {
            drinks: ["sprite,mirinda,coke,pepsi"],
            price: 70
        },
        mineralWater = {
            small: 60,
            large: 90

        },
        branches =
        ["DoDarya,Shaheed Millat Road & north nazimabad"],

        forReservatios = {
            reservationsatkababjeescom
        },


contactInfo = {
    Phone: 021 - 111 - 666 - 111
},

    description =
    {
        "Kababjees, a perfect place to rejoice variety of cuisines with your love ones, to soak in the relaxing decor & desire to revisit for once is never enough",

},
partnership =
    ["foodpanda, jobolo"],

    }

    
}
